### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by FranJNS** [SBCV/Blender-Addon-Photogrammetry-Importer#27] opened 2020-11-01 19:45 UTC
Hello, I would like that the instalation of add-on in Blender don't works. Thank you.

**Comment by SBCV** [comment] 2020-11-01 19:50
Can you please describe in more detail, what you have tried, and what exactly did not work?

**Comment by unity2k** [comment] 2020-11-01 19:53
FranJNS, if you are trying to install this on 2.92 Alpha...I've had the same problem but that's typical of plugins on experimental builds.

**Comment by robertguetzkow** [comment] 2020-11-05 09:36
The issue is that the `bl_info` in `__init__.py`  should not contain string concatenation with `+`.

**Comment by SBCV** [comment] 2020-11-05 09:41
Oh, thank you for reporting this. The problem didn't appear when starting Blender with the VScode extension - so I was not aware of that. Do you want to submit a PR?

**Comment by SBCV** [comment] 2020-11-05 21:00
Should be fixed with the latest commit. (Btw: added a new release with the latest changes)
Feel free to reopen, if the problem persists.

**Closed by SBCV** 2020-11-05 21:00 UTC
