### ISSUE TITLE
Export Screenshot Sequence

### ISSUE THREAD

**Issue by scottsegler** [SBCV/Blender-Addon-Photogrammetry-Importer#47] opened 2022-05-08 22:52 UTC
I apologize if I am doing something wrong.  Export Screenshot Sequence always worked for me in previous versions of the addon with Blender 2.8.  With Version 3.0 of the addon using Blender 3.1.2, I get the following message when executing Export Screenshot Sequence:  

Python: Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\panels\screenshot_operators.py", line 137, in execute
    bpy.ops.screen.screenshot(
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "full" unrecognized

location: <unknown location>:-1

Export screenshot sequence: ...
Output File Path: C:\Users\MyName\Downloads\Stabilize Project\Blender\Screenshot\00001.png
Python: Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\photogrammetry_importer\panels\screenshot_operators.py", line 137, in execute
    bpy.ops.screen.screenshot(
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "full" unrecognized

location: <unknown location>:-1

**Comment by SBCV** [comment] 2022-05-09 07:00
Sounds like a bug - thank you for reporting. I'll have a look in the next few days.

**Comment by scottsegler** [comment] 2022-05-09 21:19
Thanks so much and thank you for all of your contributions to this project. Your work on this is exceptional!

**Comment by SBCV** [comment] 2022-05-11 07:24
> Thanks so much and thank you for all of your contributions to this project. Your work on this is exceptional!

Thank you - nice to hear that :)

The bug was caused by a recent api change of blender - should be fixed in the latest commit https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/commit/563b6c4dc13c021e97f4c27de69dada9890ba0a8.

You find the corresponding release here: https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/releases/tag/v2022.05.11

If you experience still problems, let me know.

**Closed** 2022-05-13 09:38 UTC
