### ISSUE TITLE
Regard3D/OpenMVG workflow

### ISSUE THREAD

**Issue by SteampunkIslande** [SBCV/Blender-Addon-Photogrammetry-Importer#18] opened 2020-05-31 14:14 UTC
Hello everyone,
For those who didn't read the first issue I posted, this is about problems that can araise with the Regard3D/OpenMVG workflow.

This addon relies on json files for Regard3D/OpenMVG import. OpenMVG has a tool to convert sfm_data.bin to cameras.json (using openMVG_main_ConvertSfM_DataFormat.exe -i sfm_data.bin -o cameras.json -V -I -E (-S -C are optionnal)).

Using this simple command line, one can convert Regard3D sfm_data files into camera info as json files. So far so good.

The main issue is that this command line creates json file that this addon cannot parse correctly.

Here is the intrinsics that seem to cause the bug:

"intrinsics": [
        {
            "key": 0,
            "value": {
                "polymorphic_id": 2147483649,
                "polymorphic_name": "pinhole_radial_k3",
                "ptr_wrapper": {
                    "id": 2147483745,
                    "data": {
                        "width": 4000,
                        "height": 6000,
                        "focal_length": 15193.06853136843,
                        "principal_point": [
                            2010.6631635894829,
                            3013.5288307892844
                        ],
                        "disto_k3": [
                            0.23547542621624013,
                            1.0377324669468973,
                            25.664009974069687
                        ]
                    }
                }
            }
        },
        {
            "key": 1,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483746,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 26837.64213005792,
                        "principal_point": [
                            3024.948789263701,
                            2005.5551594699007
                        ],
                        "disto_k3": [
                            1.308115485771672,
                            23.88648384690404,
                            -560.0914521542329
                        ]
                    }
                }
            }
        },
        {
            "key": 2,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483747,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 25512.9448045926,
                        "principal_point": [
                            3061.900325109015,
                            1997.2968905128087
                        ],
                        "disto_k3": [
                            1.5001251036783452,
                            -26.644358754059213,
                            1921.1474880697998
                        ]
                    }
                }
            }
        },
        {
            "key": 3,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483748,
                    "data": {
                        "width": 4000,
                        "height": 6000,
                        "focal_length": 14108.98059220295,
                        "principal_point": [
                            2004.5743060023872,
                            3021.6981645876114
                        ],
                        "disto_k3": [
                            0.136069949695253,
                            0.7672774745376262,
                            16.480312185674408
                        ]
                    }
                }
            }
        },
        {
            "key": 4,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483749,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 14123.264459113307,
                        "principal_point": [
                            3046.6720924000785,
                            2035.155786688224
                        ],
                        "disto_k3": [
                            0.03136966972788541,
                            7.1919426547408709,
                            -114.82146264426034
                        ]
                    }
                }
            }
        },
        {
            "key": 5,
            "value": {
                "polymorphic_id": 1,
                "ptr_wrapper": {
                    "id": 2147483750,
                    "data": {
                        "width": 6000,
                        "height": 4000,
                        "focal_length": 17775.452419755573,
                        "principal_point": [
                            3034.855326792158,
                            2035.176286944217
                        ],
                        "disto_k3": [
                            0.42808247529376267,
                            6.4239000531778649,
                            -58.24064251915535
                        ]
                    }
                }
            }
        }
    ]

The parser needs to find "polymorphic_name" in every intrinsic field. What is weird is that the property is only in the first intrinsic parameter.

So either the parser could consider only first "polymorphic_name" key (in first intrinsic) or the OpenMVG converter should add this key to the json file. For the former though, according to [the doc](https://openmvg.readthedocs.io/en/latest/software/SfM/SfM_OutputFormat/), OpenMVG uses cereal to serialize sfm_data, so the latter is to blame I guess.

**Comment by SBCV** [comment] 2020-06-01 19:38
I guess that adjusting the json parser should be the most simple (and fastest) solution.
Can you share a json file with full camera poses (i.e. intrinsic and extrinsic parameters) so I  am able to test the changes?

**Comment by SteampunkIslande** [comment] 2020-06-03 09:32
Here is a json file with radial k3 parameters and definition of 'polymorphic_name' present only once in the first intrinsic.
[cameras.txt](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/files/4722313/cameras.txt)

**Comment by SBCV** [comment] 2020-06-03 19:41
Fixed in the latest commit - can you verify that everything is working for you?

**Comment by SteampunkIslande** [comment] 2020-06-04 13:11
Works well for me, though I would like to add some side notes.
First, I tried the addon with blender 2.8 and it works great.
Second, I had a weird issue with polymorphic_name key error, which I fixed by deleting only the addon directory inside blender's roaming folder.

So the latter might be the way to solve any problem related to older version of a given addon.

Just curious to know how to update an addon correctly by cleanly uninstall every previous version

**Comment by SBCV** [comment] 2020-06-05 20:16
If I am not mistaken, someone reported problems with 2.8 while view background images (therefore, the note w.r.t. Blender 2.81). 
Thank you for the feedback regarding the deletion of a previous version. If it appears again, could you maybe check, if deleting the old version within Blender works too?  (I had errors because of an old version only once, and could not reproduce it)

**Closed** 2020-06-05 21:45 UTC
