### ISSUE TITLE
Meshroom format no longer imports SFM points in v3.1.2

### ISSUE THREAD

**Issue by VisionaryMind** [SBCV/Blender-Addon-Photogrammetry-Importer#51] opened 2022-06-14 14:11 UTC
Today, I upgraded to v3.1.2 of this add-on, and now, Meshroom import for ConvertSFMFormatNode no longer generates points for the sparse cloud. I was hoping that in v3.1.2, another longstanding issue has been fixed (the inability to export points in Colmap format). Even in an older plugin version (3.0.0), Meshroom points would import properly, but would disappear when attempting to export to Colmap (the points3d.bin file is completely empty). It would be nice to have the ability to convert between Meshroom and Colmap formats. Please let me know when you expect this functionality to be working. The [other add-in](https://github.com/stuarta0/blender-photogrammetry) is also unable to generate points from Meshroom data.

**Comment by SBCV** [comment] 2022-06-16 21:27
> Today, I upgraded to v3.1.2 of this add-on, and now, Meshroom import for ConvertSFMFormatNode no longer generates points for the sparse cloud.

I can not reproduce your issue. I've used Ubuntu 18.04, Blender 3.1.2, Meshroom 2021.1.0 and the latest commit of the addon. Did you maybe forget to create a `ConvertSfMFormat` node? See the corresponding [documentation](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/import.html#meshroom).

> Even in an older plugin version (3.0.0), Meshroom points would import properly, but would disappear when attempting to export to Colmap (the points3d.bin file is completely empty)

Adding the 3D points (for Opengl point clouds) should be easy. However, adding the full feature information is not straight forward. This is the reason why it is not implemented at the moment. Loading and parsing all feature information (such as feature locations and image ids) has two downsides: 1) Loading feature information slows down the import of point clouds (and in many cases this information is not required). 2) The definition of feature information differs for the different tools (i.e. the conversion of this information introduces an additional slow-down).

One possibility would be to add another option to toggle the import of feature information. Unfortunately, this has a rather low priority for me. However, you are welcome to provide a PR.

If you are interest in the conversion of colmap models, this [library](https://github.com/naver/kapture) might be useful.

**Comment by VisionaryMind** [comment] 2022-06-17 02:06
@SBCV, thank you for the quick response. I was eventually able to get this working. Here are the steps I took:

1. When importing the Meshroom data, check _Add Points as Mesh Object_
2. With cameras and mesh-object points selected, export to Colmap.

This generates the points3d.bin, as needed. Yes, I was using the ConvertSfMFormat node. Points have loaded automatically in the past, and I do not see what is causing this behavior. At least the mesh-object points work around the problem properly.

**Comment by SBCV** [comment] 2022-06-19 20:14
> Points have loaded automatically in the past, and I do not see what is causing this behavior.

Does that mean you are not seeing the points drawn with OpenGL? Does this also happen if you import the [colmap example](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/tree/master/examples/colmap_example_model_bin)?

**Comment by VisionaryMind** [comment] 2022-06-20 19:29
> Does that mean you are not seeing the points drawn with OpenGL? Does this also happen if you import the [colmap example](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer/tree/master/examples/colmap_example_model_bin)?

Both the Colmap and Meshroom JSON examples import without a problem. Importing using a ConvertSFMFormat node (as an .SFM file), exported from the latest Meshroom build does not drawn OpenGL points. Perhaps something has changed in Meshroom code that this add-on is not able to read. At least importing the points as a mesh can workaround the problem for now.

**Comment by SBCV** [comment] 2022-06-20 21:23
> Importing using a ConvertSFMFormat node (as an .SFM file), exported from the latest Meshroom build does not draw OpenGL points. ... At least importing the points as a mesh can workaround the problem for now.

Just to avoid any confusion, are we talking about "Add Points as Mesh Object", i.e. [Option 1: Representing the points with vertices of a Blender object](https://blender-addon-photogrammetry-importer.readthedocs.io/en/latest/point_cloud.html#option-1-representing-the-points-with-vertices-of-a-blender-object)?

If yes, this makes little sense, since first the add-on parses Meshroom's directory, which results in a set of points. This set of points is then used to generate one of the different point cloud representations within Blender (i.e. "Draw Points in the 3D View with OpenGL", "Add Points as Particle System" or "Add Points as Mesh Object"). That means either all point representations should work - or none at all.

Can you share an example project? Maybe the SFM file?

**Comment by SBCV** [comment] 2022-07-02 17:08
Exporting the 3D position of points of opengl point clouds has been fixed in 13914a2604a4dca3c33bcbc479f6da3e3147259e

**Closed** 2022-08-12 13:56 UTC
